name: linting-linux

on:
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'

jobs:
  linting-and-testing:
    runs-on: Ubuntu-22.04

    steps:
    - name: Cloning SAGA
      uses: actions/checkout@v2

    - name: Installing SUMO
      run: |
        sudo add-apt-repository ppa:sumo/stable
        sudo apt-get update
        sudo apt-get install sumo sumo-tools

    - name: Installing SAGA Requirements
      run: |
        sudo pip3 install --no-cache-dir -r requirements.txt

    - name: Installing Testing & Development Requirements
      run: |
        sudo pip3 install --no-cache-dir -r requirements_dev.txt

    - name: Run Black, ISort and PyLint
      run: |
        bash test_linting.sh
    
    - name: Run PyTest
      run: |
        export SUMO_HOME='/usr/share/sumo'
        bash pytest.sh
